---
engines:
  rubocop: []
  duplication:
    minTokenMatch: 20
    skipLexicalErrors: false
    ignoreLiterals: false
    ignoreIdentifiers: true
    ignoreAnnotations: false
    ignoreUsings: false
  metric: []
languages:
  css:
    extensions:
      - '.scss'
exclude_paths:
  - "public/assets/**"