---
engines:
  rubocop:
    exclude_paths:
      - config/engines.yml
  duplication:
    exclude_paths:
      - config/engines.yml
  metric:
    exclude_paths:
      - config/engines.yml
languages:
  css:
    extensions:
      - '.scss'
exclude_paths:
  - "Public/assets/css/**"
