name: "tagged-release"

on:
  push:
    branches:
      - "dev"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "Build & test"
        run: |
          echo "done!"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{secrets.GITHUB_TOKEN}}"
          automatic_release_tag: "latest-dev"
          title: "Latest Dev Release"
          prerelease: true
          draft: false
          upload_url: "https://raw.githubusercontent.com/axtonprice-dev/quickblaze-encrypt/latest/LICENSE"
          files: |
            LICENSE
            *.md
